name: konsi_test
description: "A new Flutter project."

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.4.4 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.6
  bloc: ^8.1.2
  flutter_bloc: ^8.1.3
  dartz: ^0.10.1
  equatable: ^2.0.5
  get_it: ^7.7.0
  go_router: ^14.2.7
  google_maps_flutter: ^2.9.0
  http: ^1.2.2
  hive_flutter: ^1.1.0
  path_provider: ^2.0.2
  bloc_test: ^9.1.7
  flutter_svg: ^2.0.10+1

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^4.0.0
  mocktail: ^1.0.0
  build_runner: ^2.0.0
  hive_generator: ^2.0.1
  hive: ^2.0.4

flutter:
  assets:
    - assets/
    - assets/icons/
  uses-material-design: true